### PR TITLE
Fix change column name start/end to annotationstart/annotationend Postgres

### PR DESCRIPTION
**Pull request by NinaHerrmann**
Hello everbody, 
we really like the plugin :) 
However we also experienced the issue in #4  (end/start can not be used as column names in postgres). The pull request fix this issue by renaming the column (upgrade script renaming etc.). Is this interesting for you? 
Please contact me in case you need any other information! 
Cheers!

### CODE REVIEW

**Comment by dtnolte** [comment]
Hi NinaHermann,
a big thank you for your pull-request and sorry for my late reply. 
Im working on a new version for the plugin right now to fix both issues #3 and #4. I have incorporated and tested your code from the pull-request (again, awesome work!) but found two issues. The renaming of the db columns is not working for other db types. And there was one renaming in the annotations.js too much that leads to the storage of a wrong value for the renamed fields (which among other things messed up the sorting of the annotations).
I have fixed these issues in my code and am now testing the new version against a moodle with a postgreSQL database.
When im done with this (hopefully in the next 14 days) i will release a new version of the plugin here and in moodle.
I hope it is okay for you if i close the pull-request then without merging it (as i have already incorporated your code and fixed the issues i descibed above). In any case, a big thank you for your good work and your help to improve the Margic plugin. If you have any questions or comments, just let me know.

**Comment by NinaHerrmann** [comment]
Hey @dtnolte,
thanks for your reply (I would not call it late :slightly_smiling_face:  )!

Just for interest how does `annotationstart`/`annotationend` conflict with db-types? :thinking: 
I am sorry, I mixed things up (luckily not merged!), and I am looking forward to the new release. One other minor questions, will that release also remove the usage of `' ` for csv files [(here)](https://github.com/coactum/moodle-mod_margic/blob/2556c4817a5174f6c8a05bb03eddb92baef24636/classes/local/helper.php#L234)?
We experienced problems with this as well. 
Cheers and thank you so much!

**Comment by dtnolte** [comment]
Hey @NinaHerrmann,
I am happy to announce that I have completed my tests and have just published the new release here on github. It fixes the issues with creating entries and annotations on Moodles with pq databases as well as the error with the csv download you reported above (thank you very much for this too!).

The names 'annotationstart' and 'annotationend' were just fine by the way, only your [upgrade mechanism](https://github.com/learnweb/moodle-mod_margic/blob/fix/dbcolumnnaming/db/upgrade.php) makes a problem in Moodles with e. g. MariaDBs. Your way of defining the fields to be renamed in line 37 and 38 apparently seems to be suspicious to MariaDBs, so I have [changed it a bit using moodle constants](https://github.com/coactum/moodle-mod_margic/blob/master/db/upgrade.php).

I will now also make a new version in the moodle repository. It would be cool if you can test it on your systems and let me know if everything works as intended.

I would close this pull-request for now. If any problems or questions arise or if you have more feedback, feel free to post them in the issue tracker.

Thanks again for your awesome work to improve the margic plugin!

**Comment by NinaHerrmann** [comment]
Hey @dtnolte,
Uh good to know, I have never worked with mariadb so I will pay attention to it!
Thank you so much for your feedback, explanation, release,... :partying_face: 

Unfortunately, as we just did our major update we will need some time to test the new version, but as soon as we are ready I will update you thank you so much for your fast replies!

**Pull request closed without merging**
